/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  boost2.c                                      */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#include <stdio.h>
#include <math.h>
#include "boost2.h"

/*======================================================*/
/*  Common function to compute a fuzzy number           */
/*======================================================*/

static double compute(FuzzyNumber fn,double x) {
 int length = fn.length;
 int i;
 double imp = fn.imp(fn.degree[0],fn.conc[0].equal(x));
 double mu = imp

 for(i=1; i<length; i++) {
  imp = fn.imp(fn.degree[i],fn.conc[i].equal(x));
  mu = fn.also(mu,imp);
 }
 return mu;
}

/*======================================================*/
/*  MembershipFunction MF_xfl_trapezoid                 */
/*======================================================*/

/*------------------------------------------------------*/
/* Function to compute an equal relationship            */
/*------------------------------------------------------*/

static double MF_xfl_trapezoid_equal(double x, double min, double max, double step, double a, double b, double c, double d) {
    return (x<a || x>d? 0: (x<b? (x-a)/(b-a) : (x<c?1 : (d-x)/(d-c)))); 

}

/*======================================================*/
/*  MembershipFunction MF_xfl_triangle                  */
/*======================================================*/

/*------------------------------------------------------*/
/* Function to compute an equal relationship            */
/*------------------------------------------------------*/

static double MF_xfl_triangle_equal(double x, double min, double max, double step, double a, double b, double c) {
    return (a<x && x<=b? (x-a)/(b-a) : (b<x && x<c? (c-x)/(c-b) : 0)); 

}

/*======================================================*/
/*  Operatorset OP_op                                   */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the operator AND                      */
/*------------------------------------------------------*/

static double OP_op_And(double a, double b) {
    return (a<b? a : b); 

}

/*------------------------------------------------------*/
/* Description of the operator ALSO                     */
/*------------------------------------------------------*/

static double OP_op_Also(double a, double b) {
    return (a>b? a : b); 

}

/*------------------------------------------------------*/
/* Description of the operator IMPLICATION              */
/*------------------------------------------------------*/

static double OP_op_Imp(double a, double b) {
    return (a<b? a : b); 

}

/*------------------------------------------------------*/
/* Description of the defuzzification method            */
/*------------------------------------------------------*/

static double OP_op_Defuz(FuzzyNumber mf) {
 double min = mf.min;
 double max = mf.max;
 double step = mf.step;
     double x, m, num=0, denom=0;
     for(x=min; x<=max; x+=step) {
      m = compute(mf,x);
      num += x*m;
      denom += m;
     }
     if(denom==0) return (min+max)/2;
     return num/denom;

}


/*======================================================*/
/*  Type TP_error                                       */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label nb                          */
/*------------------------------------------------------*/

static double TP_error_nb_equal(double x){
   return MF_xfl_trapezoid_equal(x,-15.0,15.0,0.5,-18.75,-15.0,-11.25,-7.5);
}

/*------------------------------------------------------*/
/* Description of the label nm                          */
/*------------------------------------------------------*/

static double TP_error_nm_equal(double x){
   return MF_xfl_triangle_equal(x,-15.0,15.0,0.5,-11.25,-7.5,-3.75);
}

/*------------------------------------------------------*/
/* Description of the label ns                          */
/*------------------------------------------------------*/

static double TP_error_ns_equal(double x){
   return MF_xfl_triangle_equal(x,-15.0,15.0,0.5,-7.5,-3.75,0.0);
}

/*------------------------------------------------------*/
/* Description of the label ze                          */
/*------------------------------------------------------*/

static double TP_error_ze_equal(double x){
   return MF_xfl_triangle_equal(x,-15.0,15.0,0.5,-3.75,0.0,3.75);
}

/*------------------------------------------------------*/
/* Description of the label ps                          */
/*------------------------------------------------------*/

static double TP_error_ps_equal(double x){
   return MF_xfl_triangle_equal(x,-15.0,15.0,0.5,0.0,3.75,7.5);
}

/*------------------------------------------------------*/
/* Description of the label pm                          */
/*------------------------------------------------------*/

static double TP_error_pm_equal(double x){
   return MF_xfl_triangle_equal(x,-15.0,15.0,0.5,3.75,7.5,11.25);
}

/*------------------------------------------------------*/
/* Description of the label pb                          */
/*------------------------------------------------------*/

static double TP_error_pb_equal(double x){
   return MF_xfl_trapezoid_equal(x,-15.0,15.0,0.5,7.5,11.25,15.0,18.75);
}

/*======================================================*/
/*  Type TP_ce                                          */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label nb                          */
/*------------------------------------------------------*/

static double TP_ce_nb_equal(double x){
   return MF_xfl_trapezoid_equal(x,-0.4,0.4,0.013333333333333334,-0.5,-0.4,-0.30000000000000004,-0.2);
}

/*------------------------------------------------------*/
/* Description of the label nm                          */
/*------------------------------------------------------*/

static double TP_ce_nm_equal(double x){
   return MF_xfl_triangle_equal(x,-0.4,0.4,0.013333333333333334,-0.30000000000000004,-0.2,-0.09999999999999998);
}

/*------------------------------------------------------*/
/* Description of the label ns                          */
/*------------------------------------------------------*/

static double TP_ce_ns_equal(double x){
   return MF_xfl_triangle_equal(x,-0.4,0.4,0.013333333333333334,-0.2,-0.09999999999999998,0.0);
}

/*------------------------------------------------------*/
/* Description of the label ze                          */
/*------------------------------------------------------*/

static double TP_ce_ze_equal(double x){
   return MF_xfl_triangle_equal(x,-0.4,0.4,0.013333333333333334,-0.09999999999999998,0.0,0.09999999999999998);
}

/*------------------------------------------------------*/
/* Description of the label ps                          */
/*------------------------------------------------------*/

static double TP_ce_ps_equal(double x){
   return MF_xfl_triangle_equal(x,-0.4,0.4,0.013333333333333334,0.0,0.09999999999999998,0.20000000000000007);
}

/*------------------------------------------------------*/
/* Description of the label pm                          */
/*------------------------------------------------------*/

static double TP_ce_pm_equal(double x){
   return MF_xfl_triangle_equal(x,-0.4,0.4,0.013333333333333334,0.09999999999999998,0.20000000000000007,0.30000000000000004);
}

/*------------------------------------------------------*/
/* Description of the label pb                          */
/*------------------------------------------------------*/

static double TP_ce_pb_equal(double x){
   return MF_xfl_trapezoid_equal(x,-0.4,0.4,0.013333333333333334,0.2,0.30000000000000004,0.4,0.5);
}

/*======================================================*/
/*  Type TP_op                                          */
/*======================================================*/

/*------------------------------------------------------*/
/* Description of the label nb                          */
/*------------------------------------------------------*/

static double TP_op_nb_equal(double x){
   return MF_xfl_trapezoid_equal(x,-1.0,1.0,0.03333333333333333,-1.25,-1.0,-0.75,-0.5);
}

/*------------------------------------------------------*/
/* Description of the label nm                          */
/*------------------------------------------------------*/

static double TP_op_nm_equal(double x){
   return MF_xfl_triangle_equal(x,-1.0,1.0,0.03333333333333333,-0.75,-0.5,-0.25);
}

/*------------------------------------------------------*/
/* Description of the label ns                          */
/*------------------------------------------------------*/

static double TP_op_ns_equal(double x){
   return MF_xfl_triangle_equal(x,-1.0,1.0,0.03333333333333333,-0.5,-0.25,0.0);
}

/*------------------------------------------------------*/
/* Description of the label ze                          */
/*------------------------------------------------------*/

static double TP_op_ze_equal(double x){
   return MF_xfl_triangle_equal(x,-1.0,1.0,0.03333333333333333,-0.1,0.0,0.1);
}

/*------------------------------------------------------*/
/* Description of the label ps                          */
/*------------------------------------------------------*/

static double TP_op_ps_equal(double x){
   return MF_xfl_triangle_equal(x,-1.0,1.0,0.03333333333333333,0.0,0.25,0.5);
}

/*------------------------------------------------------*/
/* Description of the label pm                          */
/*------------------------------------------------------*/

static double TP_op_pm_equal(double x){
   return MF_xfl_triangle_equal(x,-1.0,1.0,0.03333333333333333,0.25,0.5,0.75);
}

/*------------------------------------------------------*/
/* Description of the label pb                          */
/*------------------------------------------------------*/

static double TP_op_pb_equal(double x){
   return MF_xfl_trapezoid_equal(x,-1.0,1.0,0.03333333333333333,0.5,0.75,1.0,1.25);
}

/*======================================================*/
/*  Rulebase RL_boostrule                               */
/*======================================================*/

static void RL_boostrule(double changeinerror, double error, double *duty) {
 double _rl;

 double _duty_degree[49];
 Consequent _duty_conc[49];
 FuzzyNumber _duty;
 _duty.min = -1.0;
 _duty.max = 1.0;
 _duty.step = 0.03333333333333333;
 _duty.imp = OP_op_Imp;
 _duty.also = OP_op_Also;
 _duty.length = 49;
 _duty.degree = _duty_degree;
 _duty.conc = _duty_conc;
 int _duty_i = 0;

 double _changeinerror_eq[7];
 _changeinerror_eq[0] = TP_ce_nb_equal(changeinerror);
 _changeinerror_eq[1] = TP_ce_nm_equal(changeinerror);
 _changeinerror_eq[2] = TP_ce_ns_equal(changeinerror);
 _changeinerror_eq[3] = TP_ce_ze_equal(changeinerror);
 _changeinerror_eq[4] = TP_ce_ps_equal(changeinerror);
 _changeinerror_eq[5] = TP_ce_pm_equal(changeinerror);
 _changeinerror_eq[6] = TP_ce_pb_equal(changeinerror);

 double _error_eq[7];
 _error_eq[0] = TP_error_nb_equal(error);
 _error_eq[1] = TP_error_nm_equal(error);
 _error_eq[2] = TP_error_ns_equal(error);
 _error_eq[3] = TP_error_ze_equal(error);
 _error_eq[4] = TP_error_ps_equal(error);
 _error_eq[5] = TP_error_pm_equal(error);
 _error_eq[6] = TP_error_pb_equal(error);

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ns_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[0],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ns_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[1],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ps_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ns_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ps_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[2],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ns_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ps_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[3],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_nm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ns_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ps_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[4],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ns_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ps_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[5],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[0]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ze_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[1]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_ps_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[2]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pm_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[3]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[4]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[5]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 _rl = OP_op_And(_changeinerror_eq[6],_error_eq[6]);
 _duty_degree[_duty_i] = _rl;
 _duty_conc[_duty_i].equal = TP_op_pb_equal;
 _duty_i++;

 *duty = OP_op_Defuz(_duty);
}


/*======================================================*/
/*                   Inference Engine                   */
/*======================================================*/

void boost2InferenceEngine(double error, double changeinerror, double *_d_duty) {
 double duty;
 RL_boostrule(changeinerror, error, &duty);
 *_d_duty = duty;
}

